
name: Tests 

on:
  pull_request:
    types: [opened, reopened]

jobs:
  LintAndSec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Python Lint
      run: |
        pip install flake8
        flake8 azure-vote/main.py

    - name: Is secure ?
      run: |
        pip install safety
        safety check -r azure-vote/main.py
    
  IntegrationTests:
    runs-on: ubuntu-latest
    needs: [LintAndSec]
    steps:
      - uses: actions/checkout@v3
      - name: Launch compose file
        run: |
          docker-compose up -d
          sleep 10
          if [[ $(curl -s -XGET http://localhost:8080/ | grep results | awk '{print $5}') -eq 0 ]]; then echo OK GET; else echo KO;exit 255; fi
          curl -s -XPOST http://localhost:8080/ -d 'vote=Cats'
          if [[ $(curl -s -XGET http://localhost:8080/ | grep results | awk '{print $5}') -eq 1 ]]; then echo OK GET; else echo KO;exit 255; fi
          docker-compose down


