
name: Tests 

on:
  workflow_dispatch:

jobs:
  LintAndSec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Python Lint
      run: |
        pip install flake8
        flake8 azure-vote/main.py

    - name: Is secure ?
      run: |
        pip install safety
        safety check -r azure-vote/main.py

  Build:
    runs-on: ubuntu-latest
    needs: [LintAndSec]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
    
  IntegrationTests:
    runs-on: ubuntu-latest
    needs: [LintAndSec,Build]
    steps:
      - uses: actions/checkout@v3
      - name: Launch compose file
        run: |
          docker-compose up -d
          if [[ $(curl -s -XGET http://localhost:8080/ | grep results | awk '{print $5}') -eq 0 ]]; then echo OK GET; else echo KO; fi
          if [[ $(curl -s -XPOST http://localhost:8080/ -d 'vote=Cats' | grep results | awk '{print $5}') -eq 1 ]]; then echo OK POST; else echo KO; fi
          docker-compose down


